#!/bin/bash

# Open or bring to focus the notion app.
# If notion is not running, start it.
# If notion is running, bring it to focus.

# do not proceed if wmctrl is not installed
if ! [ -x "$(command -v wmctrl)" ]
then
  echo 'Error: wmctrl is not installed' >&2
  exit 1
fi

WEB_ADDRESS='https://notion.so'
# find pid for app process
# -f includes the entire process details, including arguments and flags
APP_PID=$(pgrep -f "\-\-app=${WEB_ADDRESS}")
# find pid existing chromium --app process
CHROMIUM_PID=$(pgrep -f 'chromium --app')

# if app is not running, start it
# if app is running, focus it
if [ -z "$APP_PID" ]
then
  # when app is not running, but another chromium --app is, kill the chromium pid
  # this is a result of chromium's process architecture where opening another --app puts it under the same pid
  if [ -n "$CHROMIUM_PID" ]
  then
    kill "$CHROMIUM_PID"
  fi
  chromium "--app=${WEB_ADDRESS}"
else
  # using the pid, find the window id, then focus it
  wid=$(wmctrl -lp | grep "$APP_PID" | awk '{print $1}')
  # -R moves the window to the current desktop AND brings it to focus
  wmctrl -iR "$wid"
fi